### ISSUE TITLE
|inline doesn't load @framework.extras

### ISSUE THREAD

**Issue by AlexisWalravens** [newridetech/octobercms-inline-assets#1]
Hello,

When writing:  

`<style>{{ ['@framework.extras', 'assets/css/style.css']|inline }}</style>`
 
instead of:   

`<link href="{{ ['@framework.extras', 'assets/css/style.css']|theme }}" rel="stylesheet">`

The `|inline` filter  doesn't load the framework css file.

**Comment by mcharytoniuk** [comment]
@AlexisWalravens thanks for report. I'm on it, I'll get back to you in several hours with a fix. :)

**Comment by mcharytoniuk** [comment]
@AlexisWalravens I just published the new version of a plugin (http://octobercms.com/plugin/newride-inlineassets ), please let me know if everything is ok.

**Comment by AlexisWalravens** [comment]
All seems to work fine.  

Thanks for the quick fix. :)
