### ISSUE TITLE
Parse error: syntax error, unexpected '='  Line 20 Plugin.php

### ISSUE THREAD

**Issue by ARH-Digital** [newridetech/octobercms-inline-assets#2]
When running a ``composer update`` on an October site with this plugin installed, it calls the artisan command `` php artisan october:util set build ``

Running **ANY** artisan command from the CLI also yields the same error. Even just trying to show the artisan commands available by running ``php artisan``

    In Plugin.php line 20:
    Parse error: syntax error, unexpected '='

**Comment by mcharytoniuk** [comment]
@ARH-Digital I assumed that you are using PHP version older than 7.1. This line used http://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring . I replaced it with syntax that is parseable by older PHP versions. Please let me know if it helped. :) 

Best wishes

**Comment by mcharytoniuk** [comment]
@ARH-Digital also, if the issue prevents you from updating packages, try removing `plugins/newride/inlineassets` directory and redownload plugin using `/backend` update system. I just updated version to `1.0.4`.

**Comment by ARH-Digital** [comment]
@mcharytoniuk You are correct. My environment is running PHP 7.0
Thank you for the update, I can confirm that this is now working.
😃
